app/urls.py
from django.urls import path, re_path
from app import views
app_name = 'app'

urlpatterns = [

    # The home page
    path('', views.index, name='home'),

    # Matches any html file
    path('fetch_sensor_values_ajax_com', views.fetch_sensor_values_ajax_com,
         name='fetch_sensor_values_ajax_com'),
         
path('fetch_sensor_values_ajax_firebase', views.fetch_sensor_values_ajax_firebase, name='fetch_sensor_values_ajax_firebase'),
    re_path('info.html', views.infos, name='infos'),
    path('show_graph', views.show_graph, name='show_graph'),
    path('data_aquaponics_Humidity', views.data_aquaponics_Humidity, name='data_aquaponics_Humidity'),
    path('data_aquaponics_Temperature', views.data_aquaponics_Temperature, name='data_aquaponics_Temperature'),
    path('data_aquaponics_WaterTemp', views.data_aquaponics_WaterTemp, name='data_aquaponics_WaterTemp'),
    path('data_aquaponics_pH', views.data_aquaponics_pH, name='data_aquaponics_pH'),
    path('getname', views.getname, name='getname'),
    path('get_data_aquaponics_Humidity', views.get_data_aquaponics_Humidity, name='get_data_aquaponics_Humidity'),
    path('get_data_aquaponics_Temperature', views.get_data_aquaponics_Temperature, name='get_data_aquaponics_Temperature'),
    path('get_data_aquaponics_WaterTemp', views.get_data_aquaponics_WaterTemp, name='get_data_aquaponics_WaterTemp'),
    path('get_data_aquaponics_pH', views.get_data_aquaponics_pH, name='get_data_aquaponics_pH'),
    path('read', views.read, name='read'),
    path('get_last_date', views.get_last_date, name='get_last_date'),
   # path('get_data_aquaponics_Humidity_Date', views.get_data_aquaponics_Humidity_Date, name='get_data_aquaponics_Humidity_Date'),
    #path('get_data_aquaponics_Temperature_Date', views.get_data_aquaponics_Temperature_Date, name='get_data_aquaponics_Temperature_Date'),
   # path('get_data_aquaponics_WaterTemp_Date', views.get_data_aquaponics_WaterTemp_Date, name='get_data_aquaponics_WaterTemp_Date'),
   # path('get_data_aquaponics_pH_Date', views.get_data_aquaponics_pH_Date, name='get_data_aquaponics_pH_Date'),
    path('show_graph_com', views.show_graph_com, name='show_graph_com'),
    re_path(r'^.*\.*', views.pages, name='pages'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("authentication.urls")), # Auth routes - login / register
    path("", include("app.urls"))             # UI Kits Html files
]

core/templates/auth-reset-pass.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Reset Pass {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/evo-calendar@1.1.2/evo-calendar/css/evo-calendar.min.css"/>
<div class="auth-wrapper">
    <div class="auth-content">
        <div class="auth-bg">
            <span class="r"></span>
            <span class="r s"></span>
            <span class="r s"></span>
            <span class="r"></span>
        </div>
        <div class="card">
            <div class="card-body text-center">
                <div class="mb-4">
                    <i class="feather icon-mail auth-icon"></i>
                </div>
                <h3 class="mb-4">Reset Password</h3>
                <div class="input-group mb-3">
                    <input type="email" class="form-control" placeholder="Email">
                </div>
                <button class="btn btn-primary mb-4 shadow-2">Reset Password</button>
                <p class="mb-0 text-muted">Don’t have an account? <a href="/register.html" >Signup</a></p>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/index.html
{% extends "layouts/base.html" %} {% block title %} Dashboard {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %} {% block content %}
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/evo-calendar@1.1.2/evo-calendar/css/evo-calendar.min.css"/>
<div class="pcoded-content">
  <div class="pcoded-inner-content">
    <!-- [ breadcrumb ] start -->
    <!-- [ breadcrumb ] end -->
    <div class="main-body">
      <div class="page-wrapper">
        <!-- [ Main Content ] start -->
        <div class="row">
          <!--[ daily sales section ] start-->
          <div class="col-md-6 col-xl-4">
            <div class="card daily-sales">
              <div class="card-block">
                <h6 class="mb-4">Tempearture</h6>
                <div class="row d-flex align-items-center">
                  <div class="col-9">
                    <h3 class="f-w-300 d-flex align-items-center m-b-0">
                      {{result.Temperature.Data}}
                    </h3>
                  </div>

                  <div class="col-3 text-right" style="right: 20%;">
                    <img width="80px"  src="static/images/temperature.png">
                  </div>
                </div>
                <div class="progress m-t-30" style="height: 7px">
                  <div
                    class="progress-bar progress-c-theme2"
                    role="progressbar"
                    style="width: 100%"
                    aria-valuenow="35"
                    aria-valuemin="0"
                    aria-valuemax="100"
                  ></div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-6 col-xl-4">
            <div class="card Monthly-sales">
              <div class="card-block">
                <h6 class="mb-4">Humidity</h6>
                <div class="row d-flex align-items-center">
                  <div class="col-9">
                    <h3 class="f-w-300 d-flex align-items-center m-b-0">
                      {{result.Humidity.Data}}
                    </h3>
                  </div>
                  <div class="col-3 text-right" style="right: 20%;">
                    <img width="70px"  src="static/images/humidity.png">
                  </div>
                </div>
                <div class="progress m-t-30" style="height: 7px">
                  <div
                    class="progress-bar progress-c-theme"
                    role="progressbar"
                    style="width: 100%"
                    aria-valuenow="70"
                    aria-valuemin="0"
                    aria-valuemax="100"
                  ></div>
                </div>
              </div>
            </div>
          </div>
          <!--[ Monthly  sales section ] end-->
          <!--[ year  sales section ] starts-->
          <div class="col-md-12 col-xl-4">
            <div class="card yearly-sales">
              <div class="card-block">
                <h6 class="mb-4">Water Tempearture</h6>
                <div class="row d-flex align-items-center">
                  <div class="col-9">
                    <h3 class="f-w-300 d-flex align-items-center m-b-0">
                      {{result.WaterTemp.Data}}
                    </h3>
                  </div>
                  <div class="col-3 text-right" style="right: 20%;">
                    <img width="70px"  src="static/images/tempeau.png">
                  </div>
                </div>
                <div class="progress m-t-30" style="height: 7px">
                  <div
                    class="progress-bar progress-c-theme2"
                    role="progressbar"
                    style="width: 100%"
                    aria-valuenow="35"
                    aria-valuemin="0"
                    aria-valuemax="100"
                  ></div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-12 col-xl-4">
            <div class="card yearly-sales">
              <div class="card-block">
                <h6 class="mb-4">pH</h6>
                <div class="row d-flex align-items-center">
                  <div class="col-9">
                    <h3 class="f-w-300 d-flex align-items-center m-b-0">
                      {{result.pH.Data}}
                    </h3>
                  </div>
                  <div class="col-3 text-right" style="right: 15%;">
                    <img width="70px" height="70px" src="static/images/pH.png">
                  </div>
                </div>
                <div class="progress m-t-30" style="height: 7px">
                  <div
                    class="progress-bar progress-c-theme"
                    role="progressbar"
                    style="width: 100%"
                    aria-valuenow="70"
                    aria-valuemin="0"
                    aria-valuemax="100"
                  ></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/live.html
{% extends "layouts/base.html" %} {% block title %} Serial {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}

<link
  rel="stylesheet"
  href="/static/assets/plugins/chart-morris/css/morris.css"
/>

{% endblock stylesheets %} {% block content %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'font-awesome.css' %}" />
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/evo-calendar@1.1.2/evo-calendar/css/evo-calendar.min.css"/>
  </head>
  <body>
    <div class="container">
      <center><h1>Live Data from Arduino connected with the sensors</h1></center>
      <hr/>

      <div class="row d-flex justify-content-center">
        <div class="col-md-4"><label>Enter Com Port:</label></div>
            <div class="col-md-4" >
                <input   type="text" class="form-control col-md-2" name="com" id="comport">
            </div>
        <div class="col-md-4">
          <input
            value="Live Data from Arduino"
            type="submit"
            name="submit"
            id="btn_show_chart1"
            class="btn btn-primary"
            
          />
        </div>
      </div>

      <br />
      <hr />
      <div class="row">
        <div style="width: 100%" id="chartContainer1"></div>
      </div>
      <div style="margin-top: 40%" class="row">
        <div style="width: 100%" id="chartContainer2"></div>
      </div>
      <div style="margin-top: 40%" class="row">
        <div style="width: 100%" id="chartContainer3"></div>
      </div>
      <div style="margin-top: 40%" class="row">
        <div style="width: 100%" id="chartContainer4"></div>
      </div>
    </div>
  </body>

  <script src="{% static 'jquery-3.3.1.min.js' %}"></script>
  <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

  <script>
    $("#btn_show_chart1").click(function () {
      com=$("#comport").val();
      fill_graph_sensor1(com);
      fill_graph_sensor2(com);
      fill_graph_sensor3(com);
      fill_graph_sensor4(com);
    });
function fill_graph_sensor1() {
      var dataPoints = [];
      currentDate = new Date(), 
  rangeChangedTriggered = false;
var chart = new CanvasJS.Chart("chartContainer1", {
  theme: "light2",
	title: {
    text: "Charts Humidity",
    fontFamily: "arial black",
		fontColor: "#FF6384"
	},
  axisX: {
          title: "Time",

        },
        axisY: {
       
          title: "Humidity",
          suffix: "%",
          includeZero: true,
          maximum : 100,
        },
	data: [{
		type: "spline",
    name: "CPU Utilization",
    connectNullData: true,
    color: "#FF6384",
    xValueType: "dateTime",
    xValueFormatString: "DD MMM hh:mm TT",
    yValueFormatString: '#,##0.##"%"',
		dataPoints: dataPoints
	}]
});

      
   
updateData();

// Initial Values
var xValue = 0;
var yValue = 10;
var newDataCount = 6;
var dataLength = 20; // number of dataPoints visible at any point
var updateInterval = 900000; //miliseconds
function addData(data) {
  console.log(data.result);
            var str_array = data.result[0].split(",");
            console.log(str_array);
            dataPoints.push({
              x: Date.parse(str_array[1]),
              y: Number(str_array[0]),
            });
            xValue++;
            yValue = Number(str_array[0]);
	newDataCount = 1;
	chart.render();
	setTimeout(updateData, updateInterval);
}

function updateData() {
  $.ajax({
          type: "get",
          url: "{% url 'app:fetch_sensor_values_ajax_com' %}",
          data: {
                     'id': com
                   },
          success: function (data) {
            addData(data);
          },
          error: function () {
            console.log("error he ji");
          },
        });
}
  }
    
  function fill_graph_sensor2() {
      var dataPoints = [];

var chart = new CanvasJS.Chart("chartContainer2", {
  theme: "light2",
	title: {
		text: "Charts Temperature ",
          fontFamily: "arial black",
		      fontColor: "#4BC0C0"
	},
  axisX: {
          title: "Time",

        },
        axisY: {
          title: "Temperature",
          suffix: "°C",
          viewportMinimum: -80,
          viewportMaximum: 80
          
        },
	data: [{
		type: "spline",
    name: "CPU Utilization",
    connectNullData: true,
    color: "#4BC0C0",
    xValueType: "dateTime",
    xValueFormatString: "DD MMM hh:mm TT",
    yValueFormatString: '#,##0.##"°C"',
		dataPoints: dataPoints
	}]
});
updateData();

// Initial Values
var xValue = 0;
var yValue = 10;
var newDataCount = 6;
var dataLength = 20; // number of dataPoints visible at any point
var updateInterval = 900000; //miliseconds(15min)
function addData(data) {
  console.log(data.result);
            var str_array = data.result[1].split(",");
            console.log(str_array);
            dataPoints.push({
              x: Date.parse(str_array[1]),
              y: Number(str_array[0]),
            });
            xValue++;
            yValue = Number(str_array[0]);
	newDataCount = 1;
	chart.render();
	setTimeout(updateData, updateInterval);
}

function updateData() {
  $.ajax({
          type: "get",
          url: "{% url 'app:fetch_sensor_values_ajax_com' %}",
          data: {
                     'id': com
                   },
          success: function (data) {
            addData(data);
          },
          error: function () {
            console.log("error he ji");
          },
        });
}
  }
    
 
  
  function fill_graph_sensor3() {
      var dataPoints = [];

var chart = new CanvasJS.Chart("chartContainer3", {
  theme: "light3",
	title: {
		text: "Charts WaterTemp",
          fontFamily: "arial black",
		      fontColor: "#FFCE56"
	},
  axisX: {
          title: "Time",

        },
        axisY: {
          title: "WaterTemp",
          suffix: "°C",
          viewportMinimum: -170,
          viewportMaximum: 170
          
        },
	data: [{
		type: "spline",
    name: "CPU Utilization",
    connectNullData: true,
    color: "#FFCE56",
    xValueType: "dateTime",
    xValueFormatString: "DD MMM hh:mm TT",
    yValueFormatString: '#,##0.##"°C"',
		dataPoints: dataPoints
	}]
});
updateData();

// Initial Values
var xValue = 0;
var yValue = 10;
var newDataCount = 6;
var dataLength = 20; // number of dataPoints visible at any point
var updateInterval = 900000; //miliseconds
function addData(data) {
  console.log(data.result);
            var str_array = data.result[2].split(",");
            console.log(str_array);
            dataPoints.push({
              x: Date.parse(str_array[1]),
              y: Number(str_array[0]),
            });
            xValue++;
            yValue = Number(str_array[0]);
	newDataCount = 1;
	chart.render();
	setTimeout(updateData, updateInterval);
}

function updateData() {
  $.ajax({
          type: "get",
          url: "{% url 'app:fetch_sensor_values_ajax_com' %}",
          data: {
                     'id': com
                   },
          success: function (data) {
            addData(data);
          },
          error: function () {
            console.log("error he ji");
          },
        });
}
  }
    
  function fill_graph_sensor4() {
      var dataPoints = [];

var chart = new CanvasJS.Chart("chartContainer4", {
  theme: "light4",
	title: {
		text: "Charts pH",
    fontFamily: "arial black",
		fontColor: "#36A2EB"
	},
  axisX: {
          title: "Time",

        },
        axisY: {
          title: "pH",
          suffix: "",
          includeZero: true,
          maximum : 15,
          
        },
	data: [{
		type: "spline",
    name: "CPU Utilization",
    connectNullData: true,
    color: "#36A2EB",
    xValueType: "dateTime",
    xValueFormatString: "DD MMM hh:mm TT",
    yValueFormatString: '#,##0.##""',
		dataPoints: dataPoints
	}]
});
updateData();

// Initial Values
var xValue = 0;
var yValue = 10;
var newDataCount = 6;
var dataLength = 20; // number of dataPoints visible at any point
var updateInterval = 900000; //miliseconds
function addData(data) {
  console.log(data.result);
            var str_array = data.result[3].split(",");
            console.log(str_array);
            dataPoints.push({
              x: Date.parse(str_array[1]),
              y: Number(str_array[0]),
            });
            xValue++;
            yValue = Number(str_array[0]);
	newDataCount = 1;
	chart.render();
	setTimeout(updateData, updateInterval);
}

function updateData() {
  $.ajax({
          type: "get",
          url: "{% url 'app:fetch_sensor_values_ajax_com' %}",
          data: {
                     'id': com
                   },
          success: function (data) {
            addData(data);
          },
          error: function () {
            console.log("error he ji");
          },
        });
}
  }
    
 
  </script>
</html>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<script src="/static/assets/plugins/chart-morris/js/raphael.min.js"></script>
<script src="/static/assets/plugins/chart-morris/js/morris.min.js"></script>
<script src="/static/assets/js/pages/chart-morris-custom.js"></script>

{% endblock javascripts %}

core/templates/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %}

{% block content %}   
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/evo-calendar@1.1.2/evo-calendar/css/evo-calendar.min.css"/>
    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="feather icon-unlock auth-icon"></i>
                    </div>
                    <h3 class="mb-4">
                        Login
                    </h3>

                    <span class="mb-0 text-muted">
                        Add your credentials
                    </span>

                    <br />
                    <br />
                    
                    <form role="form" action="" method="POST">
                        {% csrf_token %}
                        
                        <br>
                        <div class="input-group mb-3">
                            <input class="form-control" placeholder="Username">
                        </div>
                        
                        <div class="input-group mb-4">
                            <input type="password" class="form-control" placeholder="password">
                        </div>
                        
                        <div class="form-group text-left">
                            <div class="checkbox checkbox-fill d-inline">
                                <input type="checkbox" name="checkbox-fill-1" id="checkbox-fill-a1" checked="">
                                <label for="checkbox-fill-a1" class="cr"> Save Details</label>
                            </div>
                        </div>
                        <button name="login" class="btn btn-primary shadow-2 mb-4">Login</button>

                    </form>

                    <p class="mb-0 text-muted">Don’t have an account? <a href="/register.html" >Signup</a></p>
                    <br />
                    <p class="mb-2 text-muted">
                        &copy; <a style="color:black">CodedThemes</a> 
                        - <a style="color:black">Aquaponics 2021</a>.
                    </p>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

core/templates/page-403.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} 403 Page {% endblock %}

{% block content %}   
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/evo-calendar@1.1.2/evo-calendar/css/evo-calendar.min.css"/>
    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="feather x-circle"></i>
                    </div>
                    <h3 class="mb-4">Error 403</h3>

                    <br />

                    <span class="mb-0 text-muted">
                        Access denied - <a href="/">Home</a> 
                    </span>

                </div>
            </div>
        </div>
    </div>

{% endblock content %}

core/templates/page-500.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} 500 Page {% endblock %}

{% block content %}   
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/evo-calendar@1.1.2/evo-calendar/css/evo-calendar.min.css"/>
    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="feather x-circle"></i>
                    </div>
                    <h3 class="mb-4">Error 500</h3>

                    <br />

                    <span class="mb-0 text-muted">
                        Server Error - <a href="/">Home</a> 
                    </span>

                </div>
            </div>
        </div>
    </div>

{% endblock content %}

core/templates/page-blank.html
{% extends "layouts/base.html" %}

{% block title %} Page Blank {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/evo-calendar@1.1.2/evo-calendar/css/evo-calendar.min.css"/>
    <div class="pcoded-content">
        <div class="pcoded-inner-content">
            <!-- [ breadcrumb ] start -->
            <div class="page-header">
                <div class="page-block">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="page-header-title">
                                <h5 class="m-b-10">Sample Page</h5>
                            </div>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i></a></li>
                                <li class="breadcrumb-item"><a href="javascript:">Sample Page</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- [ breadcrumb ] end -->
            <div class="main-body">
                <div class="page-wrapper">
                    <!-- [ Main Content ] start -->
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="card">
                                <div class="card-header">
                                    <h5>Hello card</h5>
                                </div>
                                <div class="card-block">
                                    <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- [ Main Content ] end -->
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %}

{% block content %}   
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/evo-calendar@1.1.2/evo-calendar/css/evo-calendar.min.css"/>
    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="feather icon-user-plus auth-icon"></i>
                    </div>
                    <h3 class="mb-4">
                        Register
                    </h3>

                    <span class="mb-0 text-muted">
                        Add your credentials
                    </span>

                    <br />
                    <br />

                    <!-- Hide the form on success -->
                    <form role="form" action="/">

                        <div class="input-group mb-3">
                            <input class="form-control" placeholder="Username">
                        </div>
                        
                        <div class="input-group mb-3">
                            <input type="email" class="form-control" placeholder="Email">
                        </div>

                        <div class="input-group mb-4">
                            <input type="password" class="form-control" placeholder="password">
                        </div>
                        
                        <div class="form-group text-left">
                            <div class="checkbox checkbox-fill d-inline">
                                <input type="checkbox" name="checkbox-fill-1" id="checkbox-fill-a1" checked="">
                                <label for="checkbox-fill-a1" class="cr"> Agree with <a href="#">terms</a></label>
                            </div>
                        </div>
                        <button name="register" class="btn btn-primary shadow-2 mb-4">Register</button>

                    </form>
                    
                    <p class="mb-0 text-muted">Already have an account? <a href="/login.html" >Login</a></p>
                    <br />

                    <p class="mb-2 text-muted">
                        &copy; <a style="color:black">CodedThemes</a> 
                        - <a style="color:black">Aquaponics 2021</a>.
                    </p>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

core/templates/ui-tables.html
{% extends "layouts/base.html" %} {% block title %} Charts {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}

<link
  rel="stylesheet"
  href="/static/assets/plugins/chart-morris/css/morris.css"
/>

{% endblock stylesheets %} {% block content %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'font-awesome.css' %}" />
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/evo-calendar@1.1.2/evo-calendar/css/evo-calendar.min.css"/>
    <script src="{% static 'bootstrap.min.js' %}"></script>
	<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
</head>
		<body>
			<div class="container">
			  <center><h1>The Aquaponics Database </h1></center>
			  <div class="row d-flex justify-content-center">
				<div class="col-sm-4">
					<input id="datepicker" width="270" />
				</div>
				<div class="col-md-4">
				  <input
					value="Submit"
					type="submit"
					name="submit"
					id="btn_show_chart1"
					class="btn btn-primary"
				  />
				</div>
				<br />
      			<hr />
				  {% autoescape off %}
				  <div style="width:600;height:500" class="row" id="graph"></div>
				  {{ graph|safe }}
			  </div>
  {% endautoescape %}
			</div>
			<script>
    $("#btn_show_chart1").click(function () {
      date=$("#datepicker").val();
      $.ajax({
          type: "GET",
          url: "{% url 'app:read' %}",
		  data:{
			  date:date
		  },
          success: function (data) {
			console.log("dps 1 : "+JSON.stringify(data) );
			  if(Object.keys(data).length === 0 && data.constructor === Object){
				$('#graph').html("") 
			  }else{
				$('#graph').html(data["my_data"])
			  }
          },
          error: function () {
          },
        });
    });
				$('#datepicker').datepicker({
					uiLibrary: 'bootstrap'
				});
			</script>  
		  </body>
</html>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<script src="/static/assets/plugins/chart-morris/js/raphael.min.js"></script>
<script src="/static/assets/plugins/chart-morris/js/morris.min.js"></script>
<script src="/static/assets/js/pages/chart-morris-custom.js"></script>

{% endblock javascripts %}